version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    expose:
      - "8080"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./webos-app:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
